### ISSUE TITLE
Reset password (and then create a Strapi account) for Azerothcore-only accounts

### ISSUE THREAD

**Issue by kofal** [r-o-b-o-t-o/strapi-azerothcore#1]
### Describe your feature request or suggestion in detail

If accounts already exist in the auth DB for azerothcore, and have an email associated with them _before_ the DB was linked to  Strapi, it would be a nice feature to have to allow users to reset their passwords by providing the email that exists in the DB, which will also then create an account for them in Strapi. Currently, if they do not remember their password, they will need to have their password reset in the DB manually by an admin before they can login/create an account on Strapi. 

Since the plugin is currently able to check to see that an account already exists in the auth DB and then create and tie it to a new account in Strapi if they remember their password, I'm not sure how difficult this would be to implement. 

### Describe a possible solution to your suggestion

An alternative solution would be to have a feature to perform a mass import of accounts that exist in the Auth DB but not currently in the CMS, that way once the accounts exist in the CMS, users can reset their password through normal means.

**Comment by r-o-b-o-t-o** [comment]
Hi, thanks for your interest in this project! (First issue opened 🥳)

I'm currently away on vacation until the middle of August but I'll definitely check that out once I'm back. Feel free to ping me here if I forget.

> An alternative solution would be to have a feature to perform a mass import of accounts that exist in the Auth DB but not currently in the CMS, that way once the accounts exist in the CMS, users can reset their password through normal means.

I considered this at some point but I feel like this would be counterintuitive or annoying for the users that do know their password. I think that the other way you suggested is much more interesting.
